
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY Level-2/go.mod Level-2/go.sum ./
RUN go mod download

COPY Level-2/server.go .

RUN go build -o server server.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./server"]
