version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file: ".env"

  client1:
    build:
      context: .
      dockerfile: dockerfile.client
    networks:
      - app-network
    command: ["0", "3"]
    depends_on:
      - server

  client2:
    build:
      context: .
      dockerfile: dockerfile.client
    networks:
      - app-network
    command: ["1", "3"] 
    depends_on:
      - server

  client3:
    build:
      context: .
      dockerfile: dockerfile.client
    networks:
      - app-network
    command: ["2", "3"] 
    depends_on:
      - server

networks:
  app-network:
